#!/bin/bash
set -euo pipefail

# Adding ComplexesMonitoringTCU-M application metrics to Prometheus
# The script is idempotent: re-running it will not create a duplicate job

source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

SERVER_IP=$(detect_server_ip)
PROMETHEUS_CONFIG="/monitoring/prometheus/prometheus.yml"

# === Application parameters (change here if needed) ===
APP_JOB_NAME="ComplexesMonitoringTCU-M"
APP_HOST="192.168.192.147"
APP_PORTS=(9101 9102 9103 9104)
# =============================================================

echo "========================================="
echo "Adding ${APP_JOB_NAME} application metrics"
echo "Server IP address: ${SERVER_IP}"
echo "========================================="

# Check that the Prometheus configuration exists
if [ ! -f "${PROMETHEUS_CONFIG}" ]; then
    echo "ERROR: ${PROMETHEUS_CONFIG} not found." >&2
    echo "Run 03_install_prometheus.sh first" >&2
    exit 1
fi

# Check that the Prometheus container is running
if ! docker ps --format '{{.Names}}' | grep -q '^prometheus$'; then
    echo "ERROR: prometheus container is not running." >&2
    echo "Run 03_install_prometheus.sh first" >&2
    exit 1
fi

# Idempotency: skip adding if the job already exists
if grep -q "job_name: '${APP_JOB_NAME}'" "${PROMETHEUS_CONFIG}"; then
    echo "Job '${APP_JOB_NAME}' already exists in the config — skipping"
else
    # Append to the scrape_configs section (append is correct: scrape_configs is the last
    # top-level section in the config generated by 03_install_prometheus.sh)
    cat >> "${PROMETHEUS_CONFIG}" << EOF

  # ${APP_JOB_NAME} application metrics
  - job_name: '${APP_JOB_NAME}'
    static_configs:
      - targets:
$(for port in "${APP_PORTS[@]}"; do echo "          - '${APP_HOST}:${port}'"; done)
EOF
    echo "Job '${APP_JOB_NAME}' added to ${PROMETHEUS_CONFIG}"
fi

# Validate the configuration before restarting
echo "Validating config with promtool..."
docker exec prometheus promtool check config /etc/prometheus/prometheus.yml

# Restart Prometheus to apply the configuration
echo "Restarting Prometheus..."
docker restart prometheus

# Wait for Prometheus to be ready
wait_for_url "http://localhost:9090/-/ready" "Prometheus" 30

echo "========================================="
echo "Checking application endpoint availability:"
for port in "${APP_PORTS[@]}"; do
    if curl -fsS --max-time 5 "http://${APP_HOST}:${port}/metrics" > /dev/null 2>&1; then
        echo "  http://${APP_HOST}:${port}/metrics -> reachable"
    else
        echo "  http://${APP_HOST}:${port}/metrics -> UNREACHABLE (check the application)"
    fi
done

echo ""
echo "Target status in Prometheus:"
for port in "${APP_PORTS[@]}"; do
    HEALTH=$(curl -fsS "http://localhost:9090/api/v1/targets" 2>/dev/null \
        | jq -r --arg url "http://${APP_HOST}:${port}/metrics" \
            '.data.activeTargets[] | select(.scrapeUrl == $url) | .health' 2>/dev/null || true)
    echo "  ${APP_HOST}:${port} -> ${HEALTH:-not found in targets}"
done

echo ""
echo "========================================="
echo "${APP_JOB_NAME} application metrics added"
echo "Prometheus Targets: http://${SERVER_IP}:9090/targets"
echo "========================================="
